all: ArrayIterator.java BinopExp.java BinopExpIterator.java EmptyIterator.java Exp.java ExpIterator.java GenIterator.java IntExp.java IntExpIterator.java IntIterator.java Main.java MakeIterator.java OpIterator.java Operator.java OrIterator.java ParenExp.java ParenExpIterator.java ThreeIterator.java
	javac ArrayIterator.java BinopExp.java BinopExpIterator.java EmptyIterator.java Exp.java ExpIterator.java GenIterator.java IntExp.java IntExpIterator.java IntIterator.java Main.java MakeIterator.java OpIterator.java Operator.java OrIterator.java ParenExp.java ParenExpIterator.java ThreeIterator.java

run: all
	java Main 0
